<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# Peer Review Assignment - Data Engineer - ETL

Estimated time needed: **20** minutes

## Objectives

In this final part you will:

*   Run the ETL process
*   Extract bank and market cap data from the JSON file `bank_market_cap.json`
*   Transform the market cap currency using the exchange rate data
*   Load the transformed data into a seperate CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [ ]:
#!mamba install pandas==1.3.3 -y
#!mamba install requests==2.26.0 -y

## Imports

Import any additional libraries you may need here.

In [141]:
import glob
import pandas as pd
from datetime import datetime
import requests

As the exchange rate fluctuates, we will download the same dataset to make marking simpler. This will be in the same format as the dataset you used in the last section

In [10]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv

## Extract

### JSON Extract Function

This function will extract JSON files.

In [13]:
def extract_from_json(file_to_process):
    dataframe = pd.read_json(file_to_process)
    return dataframe

## Extract Function

Define the extract function that finds JSON file `bank_market_cap_1.json` and calls the function created above to extract data from them. Store the data in a `pandas` dataframe. Use the following list for the columns.

In [11]:
columns=['Name','Market Cap (US$ Billion)']

In [140]:
def extract():
    # Write your code here
    json_list_name = glob.glob("bank_market_cap_*.json")
    table = pd.DataFrame(columns=columns)
    for json in json_list_name:
        table = table.append(extract_from_json(json),ignore_index=True)
    return table
extracted_data =extract()
extracted_data

Empty DataFrame
Columns: [Name, Market Cap (US$ Billion)]
Index: []

<b>Question 1</b> Load the file <code>exchange_rates.csv</code> as a dataframe and find the exchange rate for British pounds with the symbol <code>GBP</code>, store it in the variable  <code>exchange_rate</code>, you will be asked for the number. Hint: set the parameter  <code>index_col</code> to 0.

In [95]:
# Write your code here
dataframe = pd.read_csv("exchange_rates.csv",index_col=0)
exchange_rate = float(dataframe.loc['GBP'])
exchange_rate

0.7323984208000001

## Transform

Using <code>exchange_rate</code> and the `exchange_rates.csv` file find the exchange rate of USD to GBP. Write a transform function that

1.  Changes the `Market Cap (US$ Billion)` column from USD to GBP
2.  Rounds the Market Cap (US$ Billion)\` column to 3 decimal places
3.  Rename `Market Cap (US$ Billion)` to `Market Cap (GBP$ Billion)`

In [97]:
def transform(extracted_data: pd.DataFrame):
    # Write your code here
    extracted_data["Market Cap (US$ Billion)"] = round(extracted_data["Market Cap (US$ Billion)"]*exchange_rate,2)
    extracted_data.rename(columns={"Market Cap (US$ Billion)":"Market Cap (GPB$ Billion)"},inplace=True)
    return extracted_data
transformed_data = transform(extracted_data)

## Load

Create a function that takes a dataframe and load it to a csv named `bank_market_cap_gbp.csv`. Make sure to set `index` to `False`.

In [98]:
def load(transformed_data: pd.DataFrame):
    # Write your code here
    transformed_data.to_csv("bank_market_cap_gbp.csv",header=True,index=False)
load(transformed_data=transformed_data)

## Logging Function

Write the logging function <code>log</code> to log your data:

In [131]:

def log(message: str):
    # Write your code here
    timestand_format ="%d/%M/%Y-%H:%M:%S"
    now = datetime.now()
    timestand = now.strftime(timestand_format)
    mess = timestand+": "+message+"\n"
    print(mess)
    with open("logfile.txt",'a') as f:
        f.write(mess)

## Running the ETL Process

Log the process accordingly using the following <code>"ETL Job Started"</code> and <code>"Extract phase Started"</code>

In [132]:
# Write your code here
log("ETL Job Started")
log("Extract phase Started")

21/08/2022-01:08:49: ETL Job Started

21/08/2022-01:08:49: Extract phase Started

### Extract

<code>Question 2</code> Use the function <code>extract</code>, and print the first 5 rows, take a screen shot:

In [124]:
# Call the function here
extracted_data = extract()

# Print the rows here
extracted_data.head(5)

                                      Name  Market Cap (US$ Billion)
0                           JPMorgan Chase                   390.934
1  Industrial and Commercial Bank of China                   345.214
2                          Bank of America                   325.331
3                              Wells Fargo                   308.013
4                  China Construction Bank                   257.399

Log the data as <code>"Extract phase Ended"</code>

In [127]:
# Write your code here
log("Extract phase Ended")

21/07/2022-01:07:21: Extract phase Ended

### Transform

Log the following  <code>"Transform phase Started"</code>

In [115]:
# Write your code here
log("Transform phase Started")

21/01/2022-01:01:53: Transform phase Started

<code>Question 3</code> Use the function <code>transform</code> and print the first 5 rows of the output, take a screen shot:

In [116]:
# Call the function here
transformed_data = transform(extracted_data=extracted_data)
# Print the first 5 rows here
transformed_data.head(5)

                                      Name  Market Cap (GPB$ Billion)
0                           JPMorgan Chase                     286.32
1  Industrial and Commercial Bank of China                     252.83
2                          Bank of America                     238.27
3                              Wells Fargo                     225.59
4                  China Construction Bank                     188.52

Log your data <code>"Transform phase Ended"</code>

In [117]:
# Write your code here
log("Transform phase Ended")

21/03/2022-01:03:13: Transform phase Ended

### Load

Log the following `"Load phase Started"`.

In [118]:
# Write your code here
log("Load phase Started")

21/03/2022-01:03:17: Load phase Started

Call the load function

In [119]:
# Write your code here
load(transformed_data=transformed_data)

Log the following `"Load phase Ended"`.

In [120]:
# Write your code here
log("Load phase Ended")

21/03/2022-01:03:59: Load phase Ended

## Authors

Ramesh Sannareddy, Joseph Santrcangelo and Azim Hirjani

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork23455645-2022-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).